blank_issues_enabled: true
contact_links:
  - name: 페이스북 그룹
    url: https://www.facebook.com/groups/163223210377229
    about: 이야기를 나누는 곳입니다
  - name: 네이버 카페
    url: https://cafe.naver.com/knuhaneulso
    about: 재학생이 주로 쓰는 커뮤니티입니다
